### ISSUE TITLE
大佬 帮忙看看这个配置可以不

### ISSUE THREAD

**Issue by always-young** [dubhe-git/B660M-i513600KF-efi#1]
![image](https://user-images.githubusercontent.com/19371766/224694658-8129627e-9410-4a36-9e57-af068d7e44aa.png)
大佬 请问这个配置可以用你这个么？

**Comment by dubhe-git** [comment]
你这个没问题啊，主要就是看 cpu 和主板。
我这个是老猿的主板，大家理论上都一样的，最多是安装完之后你定制一下 USB.
